apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
  namespace: default
data:
  user.url: http://user-internal-service-pod-qgkdj/user/
  orders.url: http://orders-internal-service-pod-dcgzn/orders/
  